#!/bin/bash
#########################################################################
# Author: Wang Wencan
# File Name: init.sh
# Description: 
#########################################################################

DIR=`dirname $0`

LIB_PATH=`readlink -m $PWD/$DIR/.never/lib`

source $LIB_PATH/sh-libs
    
ROOT_PATH=`readlink -m $LIB_PATH/../../`

_debian_install()
{
    _execute "sudo apt-get update"

    packages=`cat $ETC_PATH/apt-get.list | grep -v "#"`

    _execute "sudo apt-get install -y $packages"
}

_debian_install

#add source .never/bashrc into ~/bashrc
MY_BASHRC_PATH=$HOME_PATH/.never/bashrc
IF_SOURCE=`grep "$MY_BASHRC_PATH" $HOME_PATH/.bashrc`
[ -z "$IF_SOURCE" ] && echo "source $MY_BASHRC_PATH" >> $HOME_PATH/.bashrc

find $ROOT_PATH -maxdepth 1 -not -regex "$ROOT_PATH\(\|/init\)" -exec mv -ft $HOME_PATH {} \;
rm -r $ROOT_PATH

